language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - postgresql
before_script:
  - psql -c 'create database springify;' -U postgres
  - gradle -Pdev migrate update
