language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java8-installer
services:
  - postgresql
before_install:
  - mkdir postgres-driver
  - cd postgres-driver
  - wget https://jdbc.postgresql.org/download/postgresql-42.1.4.jar
  - cd $TRAVIS_BUILD_DIR
before_script:
  - psql -U postgres -c 'create database springify_test;'
  - psql -U postgres -c 'create role spiros with superuser login;'
  - gradle -Ptravis migrate update
script:
  - gradle -Ptravis  -Padminpwd=$ADMINPWD check
after_success:
  - bash <(curl -s https://codecov.io/bash)
